<style>
	form
	{
		padding: 25px;
		margin-top: 50px;
		border-radius: 8px;
		box-shadow: 0px 0px 20px #d6d6d6; 
	}
</style>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<?= $this->flashSession->output(); ?>
		<form method="post" action="/login">
			<div class="form-group">
				<label>İstifadəçi adı</label>
				<input name="username" class="form-control" placeholder="İstifadəçi adı" required minlength="6" maxlength="100">	
			</div>
			<div class="form-group">
				<label>Şifrə</label>
				<input type="password" name="password" class="form-control" placeholder="Şifrə" required minlength="6">	
			</div>
            <input type="hidden" name="csrf-login" value="<?= $this->session->get('csrf-login') ?>"/>
            <div align="right">
				<input type="submit" name="login" value="Daxil ol" class="btn btn-success">
				<a href="/registration" class="btn btn-primary">Qeydiyyatdan kec</a>
			</div>
		</form>
	</div>
	<div class="col-md-3"></div>
</div>
<script>window.history.pushState(null, null, '/login')</script>	