<style>
	form
	{
		padding: 25px;
		margin-top: 50px;
		border-radius: 8px;
		box-shadow: 0px 0px 20px #d6d6d6; 
	}
</style>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<?= $this->flashSession->output(); ?>
		<form method="post" action="/registration">
			<div class="form-group">
				<label>Ad</label>
				<input name="name" class="form-control" placeholder="Ad" required minlength="3" maxlength="100">	
			</div>
			<div class="form-group">
				<label>İstifadəçi adı</label>
				<input name="username" class="form-control" placeholder="İstifadəçi adı" required minlength="6" maxlength="100">	
			</div>
			<div class="form-group">
				<label>Şifrə</label>
				<input type="password" name="password" class="form-control" placeholder="Şifrə" required minlength="6">	
			</div>
			<div class="form-group">
				<label>Təkrar şifrə</label>
				<input type="password" name="repassword" class="form-control" placeholder="Təkrar şifrə" required minlength="6">	
			</div>
            <input type="hidden" name="csrf" value="<?= $this->security->getToken() ?>"/>
            <div align="right">
				<input type="submit" name="register" value="Qeydiyyatdan keç" class="btn btn-success">
				<a href="/login" class="btn btn-primary">Daxil ol</a>
			</div>
		</form>
	</div>
	<div class="col-md-3"></div>
</div>